[project]
name = "bid-allocation"
version = "0.1.0"
description = "Employee seniority-based line assignment tool for airline scheduling"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.0",
    "gunicorn>=23.0.0",
    "jinja2>=3.1.6",
]
